INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("title", "category", 100.00, '04/24/17', '08/04/17');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("title", "category", 100.00, '04/24/17', '08/04/17');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("title", "category", 100.00, '04/24/17', '08/04/17');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("title", "category", 100.00, '04/24/17', '08/04/17');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("title", "category", 100.00, '04/24/17', '08/04/17');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("title", "category", 100.00, '04/24/17', '08/04/17');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("title", "category", 100.00, '04/24/17', '08/04/17');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("title", "category", 100.00, '04/24/17', '08/04/17');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("title", "category", 100.00, '04/24/17', '08/04/17');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("title", "category", 100.00, '04/24/17', '08/04/17');

INSERT INTO users (name, age) VALUES ("name", 15);
INSERT INTO users (name, age) VALUES ("name", 15);
INSERT INTO users (name, age) VALUES ("name", 15);
INSERT INTO users (name, age) VALUES ("name", 15);
INSERT INTO users (name, age) VALUES ("name", 15);
INSERT INTO users (name, age) VALUES ("name", 15);
INSERT INTO users (name, age) VALUES ("name", 15);
INSERT INTO users (name, age) VALUES ("name", 15);
INSERT INTO users (name, age) VALUES ("name", 15);
INSERT INTO users (name, age) VALUES ("name", 15);
INSERT INTO users (name, age) VALUES ("name", 15);
INSERT INTO users (name, age) VALUES ("name", 15);
INSERT INTO users (name, age) VALUES ("name", 15);
INSERT INTO users (name, age) VALUES ("name", 15);
INSERT INTO users (name, age) VALUES ("name", 15);
INSERT INTO users (name, age) VALUES ("name", 15);
INSERT INTO users (name, age) VALUES ("name", 15);
INSERT INTO users (name, age) VALUES ("name", 15);
INSERT INTO users (name, age) VALUES ("name", 15);
INSERT INTO users (name, age) VALUES ("name", 15);

INSERT INTO pledges (amount, user_id, project_id) VALUES ("amount", 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES ("amount", 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES ("amount", 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES ("amount", 1, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES ("amount", 1, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES ("amount", 1, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES ("amount", 1, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES ("amount", 1, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES ("amount", 1, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES ("amount", 1, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES ("amount", 2, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES ("amount", 3, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES ("amount", 4, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES ("amount", 5, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES ("amount", 6, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES ("amount", 7, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES ("amount", 8, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES ("amount", 9, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES ("amount", 10, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES ("amount", 11, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES ("amount", 2, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES ("amount", 3, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES ("amount", 4, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES ("amount", 5, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES ("amount", 6, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES ("amount", 7, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES ("amount", 8, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES ("amount", 9, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES ("amount", 10, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES ("amount", 11, 1);
